AWSTemplateFormatVersion: 2010-09-09

Description: Sets up your AWS Batch Environment for running your genomics workflows

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: IAM Roles
        Parameters:
        - BatchServiceRole
        - SpotIamFleetRole
        - InstanceRole
        - JobRole
      - Label:
          default: Compute Environment Config
        Parameters:
        - SubnetIds
        - SecurityGroupIds
        - BidPercentage
        - ImageId
        - KeyPair
        - MinvCpus
        - MaxvCpus
        - DesiredvCpus
      - Label:
        - default: Isaac
        Parameters:
        - IsaacDockerImage
        - IsaacVcpus
        - IsaacMemory
      - Label:
        - default: Strelka
        Parameters:
        - StrelkaDockerImage
        - StrelkaVcpus
        - StrelkaMemory
      - Label:
        - default: SnpEff
        Parameters:
        - SnpEffDockerImage
        - SnpEffVcpus
        - SnpEffMemory
      - Label:
        - default: Samtools Stats
        Parameters:
        - SamtoolsStatsDockerImage
        - SamtoolsStatsVcpus
        - SamtoolsStatsMemory

Parameters:
  BatchServiceRole:
    Type: String
    Description: ARN for the AWS Batch Service Role
  SpotIamFleetRole:
    Type: String
    Description: ARN for the Spot Fleet Role
  InstanceRole:
    Type: String
    Description: ARN for the ECS InstanceRole
  JobRoleArn:
    Type: String
    Description: ARN for the AWS Batch Job Role

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets you want your batch compute environment to launch in. Recommend private subnets
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Security groups your instances in your batch compute environment should use
  BidPercentage:
    Type: String
    Description: Maximum spot percentage of on-demand. Should be an integer - default is 50
    MaxLength: 3
    Default: 50
    AllowedPattern: "[0-9]+"
  ImageId:
    Type: AWS::EC2::Image::Id
    Description: AMI you want your AWS Batch Compute Environment to use
    Default: ami-553d5b43
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair for EC2 instances launched in your compute environment
  MinvCpus:
    Type: String
    Description: Minimum number of CPUs in the compute environment. Default 0.
    Default: 0
    AllowedPattern: "[0-9]+"
  DesiredvCpus:
    Type: String
    Description: Desired number of CPUs in the compute environment to launch with. Default 0.
    Default: 0
    AllowedPattern: "[0-9]+"
  MaxvCpus:
    Type: String
    Description: Maximum number of CPUs in the compute environment. Should be >= than MinCpus
    AllowedPattern: "[0-9]+"
  Env:
    Type: String
    Description: Environment you are running in (e.g. Dev or Prod)
  RetryNumber:
    Type: String
    Default: "1"
    Description: Number of retries for each AWS Batch job. Integer required.
    MaxLength: 1
    AllowedPattern: "[1-9]"
    ConstraintDescription: Value between 1 and 9

  IsaacDockerImage:
    Type: String
    Description: Docker image used to run your Isaac jobs
  IsaacVcpus:
    Type: Number
    Description: vCPUs available to Isaac Jobs. Default is usually fine
    Default: 32
  IsaacMemory:
    Type: Number
    Description: Memory (in MB) available to Isaac Jobs. Default is usually fine
    Default: 80000
  StrelkaDockerImage:
    Type: String
    Description: Docker image used to run your Strelka jobs
  StrelkaVcpus:
    Type: Number
    Description: vCPUs available to Strelka Jobs. Default is usually fine
    Default: 32
  StrelkaMemory:
    Type: Number
    Description: Memory (in MB) available to Strelka Jobs. Default is usually fine
    Default: 32000
  SnpEffDockerImage:
    Type: String
    Description: Docker image used to run your snpEff jobs
  SnpEffVcpus:
    Type: Number
    Description: vCPUs available to snpEff Jobs. Default is usually fine
    Default: 4
  SnpEffMemory:
    Type: Number
    Description: Memory (in MB) available to snpEff Jobs. Default is usually fine
    Default: 10000
  SamtoolsStatsDockerImage:
    Type: String 
    Description: Docker image used to run your SAMtools jobs
  SamtoolsStatsVcpus:
    Type: Number
    Description: vCPUs available to SAMtools Jobs. Default is usually fine
    Default: 4
  SamtoolsStatsMemory:
    Type: Number
    Description: Memory (in MB) available to SAMtools Jobs. Default is usually fine
    Default: 10000

Resources:
  GenomicsComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: !Join ["-", [genomicsEnv, !Ref Env]]
      ServiceRole: !Ref BatchServiceRole
      Type: MANAGED
      State: ENABLED
      ComputeResources:
        BidPercentage: !Ref BidPercentage
        Ec2KeyPair: !Ref KeyPair
        ImageId: !Ref ImageId
        InstanceRole: !Ref InstanceRole
        InstanceTypes:
          - optimal
        MinvCpus: !Ref MinvCpus
        DesiredvCpus: !Ref DesiredvCpus
        MaxvCpus: !Ref MaxvCpus
        SecurityGroupIds: !Ref SecurityGroupIds
        SpotIamFleetRole: !Ref SpotIamFleetRole
        Subnets: !Ref SubnetIds
        Type: SPOT

  HighPriorityQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: !Join ["-", [highPriority, !Ref Env]]
      Priority: 1000
      State: ENABLED
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref GenomicsComputeEnvironment

  LowPriorityQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: !Join ["-", [lowPriority, !Ref Env]]
      Priority: 1
      State: ENABLED
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref GenomicsComputeEnvironment

  IsaacJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: !Join ["-", ["isaac", !Ref Env]]
      Type: container
      RetryStrategy:
        Attempts: !Ref RetryNumber
      ContainerProperties:
        Image: !Ref IsaacDockerImage
        Vcpus: !Ref IsaacVcpus
        Memory: !Ref IsaacMemory
        JobRoleArn: !Ref JobRoleArn
        MountPoints: 
          - ContainerPath: "/scratch"
            ReadOnly: false
            SourceVolume: docker_scratch
        Volumes:
          - Name: docker_scratch
            Host:
              SourcePath: "/docker_scratch"

  StrelkaJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: !Join ["-", ["strelka", !Ref Env]]
      Type: container
      RetryStrategy:
        Attempts: !Ref RetryNumber
      ContainerProperties:
        Image: !Ref StrelkaDockerImage
        Vcpus: !Ref StrelkaVcpus
        Memory: !Ref StrelkaMemory
        JobRoleArn: !Ref JobRoleArn
        MountPoints: 
          - ContainerPath: "/scratch"
            ReadOnly: false
            SourceVolume: docker_scratch
        Volumes:
          - Name: docker_scratch
            Host:
              SourcePath: "/docker_scratch"

  SnpEffJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: !Join ["-", ["snpeff", !Ref Env]]
      Type: container
      RetryStrategy:
        Attempts: !Ref RetryNumber
      ContainerProperties:
        Image: !Ref SnpEffDockerImage
        Vcpus: !Ref SnpEffVcpus
        Memory: !Ref SnpEffMemory
        JobRoleArn: !Ref JobRoleArn
        MountPoints: 
          - ContainerPath: "/scratch"
            ReadOnly: false
            SourceVolume: docker_scratch
        Volumes:
          - Name: docker_scratch
            Host:
              SourcePath: "/docker_scratch"

  SamtoolsStatsJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: !Join ["-", ["samtools_stats", !Ref Env]]
      Type: container
      RetryStrategy:
        Attempts: !Ref RetryNumber
      ContainerProperties:
        Image: !Ref SamtoolsStatsDockerImage
        Vcpus: !Ref SamtoolsStatsVcpus
        Memory: !Ref SamtoolsStatsMemory
        JobRoleArn: !Ref JobRoleArn
        MountPoints: 
          - ContainerPath: "/scratch"
            ReadOnly: false
            SourceVolume: docker_scratch
        Volumes:
          - Name: docker_scratch
            Host:
              SourcePath: "/docker_scratch"
